/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.saltsoft;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
        ManyWorkers mlekoOdKrowyJestSuper = new ManyWorkers();
        mlekoOdKrowyJestSuper.startManyWorkers(60);
    }

}
